name: Test
on:
  pull_request:
    branches:
      - main

jobs:
  deploy:
    name: Build & Deploy
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: client
    steps:
      - name: Code checkout
        uses: actions/checkout@v3

      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 20.x

      - name: Install client dependencies
        run: npm ci

      - name: Install server dependencies
        run: npm ci
        working-directory: server

      - name: Build app
        run: npm run build

      - name: Install Playwright browsers
        run: npx playwright install
        working-directory: server

      - name: Run E2E tests
        run: npx playwright test
        working-directory: server
